name: set-env

permissions:
  contents: read
  id-token: write

runs:
  using: 'composite'
  steps:
    - name: Load secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        repo_secrets: |
          SRCCLR_API_TOKEN=infra/data/ci/drone-plugins:srcclr_api_token
          GRAFANA_API_KEY=infra/data/ci/drone-plugins:grafana_api_key
          GCOM_PUBLISH_TOKEN=infra/data/ci/drone-plugins:gcom_publish_token
          GITHUB_TOKEN=infra/data/ci/drone-plugins:github_token
        common_secrets: |
          GAR=secret/data/common/gar:.dockerconfigjson
          GCR=secret/data/common/gcr:.dockerconfigjson
